In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results__.html
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/final_waste_research_metadata_v1.0.zip
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__notebook__.ipynb
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__output__.json
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/custom.css
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/metadata/test_bangladesh.csv
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/metadata/validation.csv
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/metadata/test_international.csv
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/metadata/train.csv
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/metadata/test.csv
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__valid__IMG_20250805_204539_jpg.rf.d11279a808844d13dbe242ba80b67caf__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(233)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__train__IMG_20250822_141541_jpg.rf.894cbd66f819a5562d44d805601476ea__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(39)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(396)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(110)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(406)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(106)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__train__IMG_20250822_141838_jpg.rf.66d8b9767b12f9674cb6ae8773eecb2d__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(378)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(432)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(167)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__valid__IMG_20250805_204236_jpg.rf.c0e12156dabeb55d93178bcb1ffeca91__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(280)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(427)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(463)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(44)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(323)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(460)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(294)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(201)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(71)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(138)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(416)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(264)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(424)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(297)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(404)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(394)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(154)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(368)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(56)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(350)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(190)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(327)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(494)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__train__IMG_20250822_141304_jpg.rf.e833de46ca1ceac6b7dfc120ea66e449__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(257)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(395)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(290)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(16)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(100)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(12)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(145)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(451)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(276)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(386)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(254)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(507)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(390)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(42)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__valid__IMG_20250805_203059_jpg.rf.8d622697f22e0251b4e7b36a45a3afec__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(305)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__valid__IMG_20250822_141223_jpg.rf.7b2a5a2c88a30385f9f63b64f3b1438a__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(426)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(455)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(200)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(439)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(445)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(318)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(277)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(117)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(309)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(33)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(7)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(158)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(297)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(179)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(293)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(124)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(71)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(40)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(147)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(420)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(429)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(257)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(126)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(465)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(367)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(277)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(395)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(348)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(125)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(415)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__train__IMG_20250803_221036_jpg.rf.ee7583280dfb467c028359c92214d93f__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(63)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(225)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(20)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(93)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(138)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(317)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(177)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__train__IMG_20250822_141515_jpg.rf.b875029247bd085bbc9448093657cd30__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__train__IMG_20250805_203205_jpg.rf.dd1bd8fd4bd54ffcc7c3556e93e79ab0__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(426)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(54)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(439)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(208)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(263)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(94)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(38)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(243)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(364)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(50)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(345)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(376)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__valid__IMG_20250805_204150_jpg.rf.51f7024e94bbed2ce3ec22459f5f7d64__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(225)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(476)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(97)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(3)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(306)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(483)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(252)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(46)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(475)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(30)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(70)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(252)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(230)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(272)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__train__IMG_20250822_141539_jpg.rf.a21e7afcf046c7a3ba68ea161ca1d8e8__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(240)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(296)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(321)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__test__IMG_20250805_205105_jpg.rf.64baa5f50ef7acfeb065e54695ae2760__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(313)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__train__IMG_20250803_221121_jpg.rf.71fd5cce1e449cd586fca754d9ffb829__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(271)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(273)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(94)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(114)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(173)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(315)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(338)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(277)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(128)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(88)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(448)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(508)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(493)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(393)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(381)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(315)_aug4.jpg

In [2]:
import torch

print("=" * 60)
print("GPU CHECK")
print("=" * 60)

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA:", torch.version.cuda)

============================================================
GPU CHECK
============================================================
PyTorch version: 2.10.0+cu128
CUDA available: True
GPU: Tesla T4
CUDA: 12.8

# #1. 1st Every Model Searching Metadata

In [3]:
from pathlib import Path
import os

print("=" * 80)
print("KAGGLE FILESYSTEM CHECK")
print("=" * 80)

print("\nWORKING DIRECTORY:")
print("/kaggle/working")
print(list(Path("/kaggle/working").iterdir()))

print("\nINPUT DIRECTORY:")
input_root = Path("/kaggle/input")

if input_root.exists():
    for item in input_root.iterdir():
        print(item)
else:
    print("No /kaggle/input")

print("\nSEARCHING FOR FINAL METADATA...")

matches = []

for root in [
    Path("/kaggle/input"),
    Path("/kaggle/working")
]:

    if root.exists():

        for path in root.rglob("final_metadata.csv"):
            matches.append(path)

print("\nFound:", len(matches))

for path in matches:
    print(path)

print("\nSEARCHING FOR TRAIN METADATA...")

matches = []

for root in [
    Path("/kaggle/input"),
    Path("/kaggle/working")
]:

    if root.exists():

        for path in root.rglob("train_final.csv"):
            matches.append(path)

print("\nFound:", len(matches))

for path in matches:
    print(path)

================================================================================
KAGGLE FILESYSTEM CHECK
================================================================================

WORKING DIRECTORY:
/kaggle/working
[PosixPath('/kaggle/working/__notebook__.ipynb')]

INPUT DIRECTORY:
/kaggle/input/notebooks

SEARCHING FOR FINAL METADATA...

Found: 2
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Waste_Dataset_Research_Metadata/final_metadata.csv
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset/research_metadata/final_metadata.csv

SEARCHING FOR TRAIN METADATA...

Found: 2
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Waste_Dataset_Research_Metadata/train_final.csv
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset/research_metadata/train_final.csv

2. ##  RESTORE FINAL RESEARCH METADATA

In [4]:
# ============================================================
# RESTORE FINAL RESEARCH METADATA
# ============================================================

from pathlib import Path
import pandas as pd

# ------------------------------------------------------------
# CORRECT KAGGLE INPUT PATH
# ------------------------------------------------------------

META = Path(
    "/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset/research_metadata"
)

print("=" * 80)
print("RESTORING FINAL RESEARCH METADATA")
print("=" * 80)

print("Metadata directory:")
print(META)

# ------------------------------------------------------------
# CHECK DIRECTORY
# ------------------------------------------------------------

if not META.exists():
    raise FileNotFoundError(
        f"Metadata directory not found:\n{META}"
    )

print("\n✓ Metadata directory found")

print("\nAvailable files:")

for f in sorted(META.iterdir()):
    print(" -", f.name)

# ------------------------------------------------------------
# LOAD METADATA
# ------------------------------------------------------------

final_df = pd.read_csv(
    META / "final_metadata.csv"
)

train_df = pd.read_csv(
    META / "train_final.csv"
)

val_df = pd.read_csv(
    META / "validation_final.csv"
)

test_df = pd.read_csv(
    META / "test_final.csv"
)

bd_test = pd.read_csv(
    META / "test_bangladesh_final.csv"
)

international_test_df = pd.read_csv(
    META / "test_international_final.csv"
)

# ------------------------------------------------------------
# RESTORE SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("DATASET RESTORED SUCCESSFULLY")
print("=" * 80)

print(
    f"Final metadata       : {len(final_df):,}"
)

print(
    f"Train                : {len(train_df):,}"
)

print(
    f"Validation           : {len(val_df):,}"
)

print(
    f"Overall Test         : {len(test_df):,}"
)

print(
    f"Bangladesh Test      : {len(bd_test):,}"
)

print(
    f"International Test   : {len(international_test_df):,}"
)

# ------------------------------------------------------------
# CONSISTENCY CHECK
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("CONSISTENCY CHECK")
print("-" * 80)

split_total = (
    len(train_df)
    + len(val_df)
    + len(test_df)
)

print(
    f"Train + Validation + Test : {split_total:,}"
)

print(
    f"Final metadata            : {len(final_df):,}"
)

print(
    "MATCH                     :",
    split_total == len(final_df)
)

# ------------------------------------------------------------
# BASIC DATA CHECK
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("CLASS DISTRIBUTION — TRAIN")
print("-" * 80)

print(
    train_df["class"]
    .value_counts()
    .sort_index()
)

print("\n" + "-" * 80)
print("SOURCE DISTRIBUTION — TRAIN")
print("-" * 80)

print(
    train_df["source"]
    .value_counts()
)

print("\n✓ METADATA RESTORATION COMPLETE")

================================================================================
RESTORING FINAL RESEARCH METADATA
================================================================================
Metadata directory:
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset/research_metadata

✓ Metadata directory found

Available files:
 - FINAL_CHECKPOINT.json
 - final_metadata.csv
 - manual_review_decisions.csv
 - test_bangladesh_final.csv
 - test_final.csv
 - test_international_final.csv
 - train_final.csv
 - training_class_balance.csv
 - validation_final.csv

================================================================================
DATASET RESTORED SUCCESSFULLY
================================================================================
Final metadata       : 10,668
Train                : 7,245
Validation           : 1,552
Overall Test         : 1,871
Bangladesh Test      : 319
International Test   : 1,289

--------------------------------------------------------------------------------
CONSISTENCY CHECK
--------------------------------------------------------------------------------
Train + Validation + Test : 10,668
Final metadata            : 10,668
MATCH                     : True

--------------------------------------------------------------------------------
CLASS DISTRIBUTION — TRAIN
--------------------------------------------------------------------------------
class
Cardboard    1193
Glass        1433
Metal        1594
Paper        1793
Plastic      1232
Name: count, dtype: int64

--------------------------------------------------------------------------------
SOURCE DISTRIBUTION — TRAIN
--------------------------------------------------------------------------------
source
International    6014
Bangladesh       1231
Name: count, dtype: int64

✓ METADATA RESTORATION COMPLETE

# # 3.CHECK ORIGINAL IMAGE PATHS

In [5]:
# ============================================================
# CHECK ORIGINAL IMAGE PATHS
# ============================================================

from pathlib import Path

print("=" * 80)
print("CHECKING ORIGINAL IMAGE PATHS")
print("=" * 80)

sample_paths = train_df["original_path"].head(20)

existing = 0
missing = 0

for p in sample_paths:

    path = Path(p)

    if path.exists():
        existing += 1
    else:
        missing += 1

print("Sample paths checked :", len(sample_paths))
print("Existing             :", existing)
print("Missing              :", missing)

if missing == 0:
    print("\n✓ Original image paths are accessible")
else:
    print(
        "\n⚠ Original image paths are NOT currently accessible"
    )

================================================================================
CHECKING ORIGINAL IMAGE PATHS
================================================================================
Sample paths checked : 20
Existing             : 0
Missing              : 20

⚠ Original image paths are NOT currently accessible

In [6]:
from pathlib import Path

META = Path(
    "/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset/research_metadata"
)

print(META)
print(META.exists())

/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset/research_metadata
True

# # 4.RESTORE FINAL RESEARCH METADATA

In [7]:
# ============================================================
# RESTORE FINAL RESEARCH METADATA
# ============================================================

from pathlib import Path
import pandas as pd

META = Path(
    "/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset/research_metadata"
)

assert META.exists(), f"Metadata directory not found: {META}"

final_df = pd.read_csv(
    META / "final_metadata.csv"
)

train_df = pd.read_csv(
    META / "train_final.csv"
)

val_df = pd.read_csv(
    META / "validation_final.csv"
)

test_df = pd.read_csv(
    META / "test_final.csv"
)

bd_test = pd.read_csv(
    META / "test_bangladesh_final.csv"
)

international_test_df = pd.read_csv(
    META / "test_international_final.csv"
)

print("=" * 80)
print("FINAL RESEARCH METADATA RESTORED")
print("=" * 80)

print(f"Final metadata       : {len(final_df):,}")
print(f"Train                : {len(train_df):,}")
print(f"Validation           : {len(val_df):,}")
print(f"Overall Test         : {len(test_df):,}")
print(f"Bangladesh Test      : {len(bd_test):,}")
print(f"International Test   : {len(international_test_df):,}")

================================================================================
FINAL RESEARCH METADATA RESTORED
================================================================================
Final metadata       : 10,668
Train                : 7,245
Validation           : 1,552
Overall Test         : 1,871
Bangladesh Test      : 319
International Test   : 1,289

# # 5.FINAL CONSISTENCY FREEZE

In [8]:
# ============================================================
# FINAL CONSISTENCY FREEZE
# ============================================================

split_total = (
    len(train_df)
    + len(val_df)
    + len(test_df)
)

print("=" * 80)
print("FINAL METADATA CONSISTENCY")
print("=" * 80)

print(f"Final metadata       : {len(final_df):,}")
print(f"Train                : {len(train_df):,}")
print(f"Validation           : {len(val_df):,}")
print(f"Overall Test         : {len(test_df):,}")

print("-" * 80)

print(
    f"Train + Validation + Test : {split_total:,}"
)

print(
    f"Final metadata            : {len(final_df):,}"
)

assert split_total == len(final_df)

print("\n✓ METADATA CONSISTENCY PASSED")

================================================================================
FINAL METADATA CONSISTENCY
================================================================================
Final metadata       : 10,668
Train                : 7,245
Validation           : 1,552
Overall Test         : 1,871
--------------------------------------------------------------------------------
Train + Validation + Test : 10,668
Final metadata            : 10,668

✓ METADATA CONSISTENCY PASSED

# 6.FIND AVAILABLE KAGGLE INPUT DATA

In [9]:
# ============================================================
# FIND AVAILABLE KAGGLE INPUT DATA
# ============================================================

from pathlib import Path

INPUT_ROOT = Path("/kaggle/input")

print("=" * 80)
print("KAGGLE INPUT DATASETS")
print("=" * 80)

for item in INPUT_ROOT.iterdir():
    print(item)

================================================================================
KAGGLE INPUT DATASETS
================================================================================
/kaggle/input/notebooks

# 7.SEARCH FOR IMAGE FILES

In [10]:
# ============================================================
# SEARCH FOR IMAGE FILES
# ============================================================

from pathlib import Path

image_extensions = {
    ".jpg",
    ".jpeg",
    ".png",
    ".webp"
}

image_files = []

for path in Path("/kaggle/input").rglob("*"):
    if path.is_file() and path.suffix.lower() in image_extensions:
        image_files.append(path)

print("=" * 80)
print("IMAGE SEARCH")
print("=" * 80)

print(
    "Images found:",
    len(image_files)
)

if image_files:
    print("\nSample images:")
    for p in image_files[:20]:
        print(p)
else:
    print("\n⚠ NO IMAGE FILES FOUND")

================================================================================
IMAGE SEARCH
================================================================================
Images found: 29977

Sample images:
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_1.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_33.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_25.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_6.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_13.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_14.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_38.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_39.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_37.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_35.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_41.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_2.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_18.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___78_0.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_28.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___73_1.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_8.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_26.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_22.png
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files/__results___72_34.png

# 8.FIND ACTUAL DATASET IMAGES

In [11]:
# ============================================================
# 8. FIND ACTUAL DATASET IMAGES
# ============================================================

from pathlib import Path
from collections import Counter
import os

INPUT_ROOT = Path("/kaggle/input")

image_extensions = {
    ".jpg",
    ".jpeg",
    ".png",
    ".webp"
}

all_images = []

for path in INPUT_ROOT.rglob("*"):
    if (
        path.is_file()
        and path.suffix.lower() in image_extensions
    ):
        all_images.append(path)

print("=" * 80)
print("TOTAL IMAGE FILES")
print("=" * 80)

print("Total images found:", len(all_images))

print("\nExtension distribution:")

extension_counts = Counter(
    p.suffix.lower()
    for p in all_images
)

for ext, count in sorted(extension_counts.items()):
    print(f"{ext:8s} : {count:,}")

================================================================================
TOTAL IMAGE FILES
================================================================================
Total images found: 29977

Extension distribution:
.jpg     : 29,885
.png     : 92

# 8.1 EXCLUDE NOTEBOOK RESULT FILES

In [12]:
# ============================================================
# 8.1 EXCLUDE NOTEBOOK RESULT FILES
# ============================================================

dataset_candidate_images = [
    p for p in all_images
    if "__results___files" not in str(p)
]

print("=" * 80)
print("DATASET IMAGE CANDIDATES")
print("=" * 80)

print(
    "All image files              :",
    len(all_images)
)

print(
    "After excluding notebook outputs:",
    len(dataset_candidate_images)
)

print("\nSample candidates:")

for p in dataset_candidate_images[:50]:
    print(p)

================================================================================
DATASET IMAGE CANDIDATES
================================================================================
All image files              : 29977
After excluding notebook outputs: 29909

Sample candidates:
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__valid__IMG_20250805_204539_jpg.rf.d11279a808844d13dbe242ba80b67caf__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(233)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__train__IMG_20250822_141541_jpg.rf.894cbd66f819a5562d44d805601476ea__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(39)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(396)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(110)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(406)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(106)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__train__IMG_20250822_141838_jpg.rf.66d8b9767b12f9674cb6ae8773eecb2d__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(378)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(432)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(167)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__valid__IMG_20250805_204236_jpg.rf.c0e12156dabeb55d93178bcb1ffeca91__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(280)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(427)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(463)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(44)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(323)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(460)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(294)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(201)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(71)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(138)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(416)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(264)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(424)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(297)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(404)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(394)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(154)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(368)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(56)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(350)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(190)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(327)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(494)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/BD__EWaste__train__IMG_20250822_141304_jpg.rf.e833de46ca1ceac6b7dfc120ea66e449__obj0.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(257)_aug3.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(395)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(290)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(16)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(100)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(12)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(145)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(451)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(276)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(386)_aug2.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(254)_aug1.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(507)_aug4.jpg
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal/INTL__Metal(390)_aug3.jpg

# 8.2 FINAL DATASET STRUCTURE CHECK

In [13]:
# ============================================================
# 8.2 FINAL DATASET STRUCTURE CHECK
# ============================================================

from pathlib import Path
from collections import Counter

DATASET_ROOT = Path(
    "/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split"
)

print("=" * 80)
print("FINAL DATASET STRUCTURE")
print("=" * 80)

print("Dataset root:")
print(DATASET_ROOT)

assert DATASET_ROOT.exists(), f"Dataset not found: {DATASET_ROOT}"

print("\nTop-level folders:")

for item in sorted(DATASET_ROOT.iterdir()):
    print(" -", item.name)

================================================================================
FINAL DATASET STRUCTURE
================================================================================
Dataset root:
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split

Top-level folders:
 - metadata
 - test
 - test_bangladesh
 - test_international
 - train
 - validation

In [14]:
# ============================================================
# 8.3 COUNT ACTUAL DATASET IMAGES
# ============================================================

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}

def count_images(folder):
    return sum(
        1
        for p in folder.rglob("*")
        if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
    )

print("=" * 80)
print("ACTUAL DATASET IMAGE COUNTS")
print("=" * 80)

for split in ["train", "validation", "test"]:

    split_path = DATASET_ROOT / split

    if split_path.exists():
        count = count_images(split_path)
        print(f"{split:12s}: {count:,}")
    else:
        print(f"{split:12s}: NOT FOUND")

================================================================================
ACTUAL DATASET IMAGE COUNTS
================================================================================
train       : 7,255
validation  : 1,555
test        : 1,880

# 8.4 CLASS-WISE IMAGE COUNT

In [15]:
# ============================================================
# 8.4 CLASS-WISE IMAGE COUNT
# ============================================================

classes = [
    "Cardboard",
    "Glass",
    "Metal",
    "Paper",
    "Plastic"
]

print("=" * 80)
print("CLASS-WISE DATASET COUNT")
print("=" * 80)

for split in ["train", "validation", "test"]:

    split_path = DATASET_ROOT / split

    print(f"\n{split.upper()}")
    print("-" * 50)

    total = 0

    for cls in classes:

        cls_path = split_path / cls

        if cls_path.exists():

            count = count_images(cls_path)

            print(f"{cls:12s}: {count:,}")

            total += count

        else:
            print(f"{cls:12s}: NOT FOUND")

    print(f"{'TOTAL':12s}: {total:,}")

================================================================================
CLASS-WISE DATASET COUNT
================================================================================

TRAIN
--------------------------------------------------
Cardboard   : 1,193
Glass       : 1,433
Metal       : 1,602
Paper       : 1,793
Plastic     : 1,234
TOTAL       : 7,255

VALIDATION
--------------------------------------------------
Cardboard   : 255
Glass       : 307
Metal       : 343
Paper       : 385
Plastic     : 265
TOTAL       : 1,555

TEST
--------------------------------------------------
Cardboard   : 272
Glass       : 372
Metal       : 388
Paper       : 484
Plastic     : 364
TOTAL       : 1,880

In [16]:
# ============================================================
# STEP 1 — RESTORE METADATA AGAIN
# ============================================================

from pathlib import Path
import pandas as pd

META = Path(
    "/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset/research_metadata"
)

assert META.exists(), f"Metadata directory not found: {META}"

final_df = pd.read_csv(META / "final_metadata.csv")
train_df = pd.read_csv(META / "train_final.csv")
val_df = pd.read_csv(META / "validation_final.csv")
test_df = pd.read_csv(META / "test_final.csv")

bd_test = pd.read_csv(META / "test_bangladesh_final.csv")
international_test_df = pd.read_csv(
    META / "test_international_final.csv"
)

print("=" * 80)
print("METADATA RESTORED")
print("=" * 80)

print(f"Final metadata : {len(final_df):,}")
print(f"Train          : {len(train_df):,}")
print(f"Validation     : {len(val_df):,}")
print(f"Test           : {len(test_df):,}")

================================================================================
METADATA RESTORED
================================================================================
Final metadata : 10,668
Train          : 7,245
Validation     : 1,552
Test           : 1,871

In [17]:
# ============================================================
# STEP 2 — DATASET ROOT
# ============================================================

DATASET_ROOT = Path(
    "/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split"
)

assert DATASET_ROOT.exists(), "Dataset root not found"

print("=" * 80)
print("DATASET ROOT")
print("=" * 80)

print(DATASET_ROOT)

print("\nAvailable folders:")

for item in DATASET_ROOT.iterdir():
    print(" -", item.name)

================================================================================
DATASET ROOT
================================================================================
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split

Available folders:
 - metadata
 - validation
 - test_international
 - test_bangladesh
 - test
 - train

In [18]:
# ============================================================
# STEP 3 — METADATA VS ACTUAL DATASET
# ============================================================

IMAGE_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".webp"
}

def count_images(folder):
    return sum(
        1
        for p in folder.rglob("*")
        if p.is_file()
        and p.suffix.lower() in IMAGE_EXTENSIONS
    )

print("=" * 80)
print("METADATA VS ACTUAL DATASET")
print("=" * 80)

metadata_counts = {
    "train": len(train_df),
    "validation": len(val_df),
    "test": len(test_df)
}

actual_counts = {
    "train": count_images(DATASET_ROOT / "train"),
    "validation": count_images(DATASET_ROOT / "validation"),
    "test": count_images(DATASET_ROOT / "test")
}

for split in ["train", "validation", "test"]:

    m = metadata_counts[split]
    a = actual_counts[split]

    print(
        f"{split:12s} | "
        f"Metadata = {m:,} | "
        f"Actual = {a:,} | "
        f"Difference = {a-m:+,}"
    )

print("-" * 80)

print(
    f"Metadata Total : {sum(metadata_counts.values()):,}"
)

print(
    f"Actual Total   : {sum(actual_counts.values()):,}"
)

================================================================================
METADATA VS ACTUAL DATASET
================================================================================
train        | Metadata = 7,245 | Actual = 7,255 | Difference = +10
validation   | Metadata = 1,552 | Actual = 1,555 | Difference = +3
test         | Metadata = 1,871 | Actual = 1,880 | Difference = +9
--------------------------------------------------------------------------------
Metadata Total : 10,668
Actual Total   : 10,690

In [19]:
# ============================================================
# STEP 4 — FIND EXTRA / MISSING IMAGES
# ============================================================

print("=" * 80)
print("CHECKING METADATA ↔ ACTUAL IMAGE MAPPING")
print("=" * 80)

def normalize_path(p):
    return str(p).replace("\\", "/").strip()

# ------------------------------------------------------------
# Create actual image records
# ------------------------------------------------------------

actual_records = []

for split in ["train", "validation", "test"]:

    split_path = DATASET_ROOT / split

    for cls in classes:

        class_path = split_path / cls

        if not class_path.exists():
            continue

        for img in class_path.rglob("*"):

            if (
                img.is_file()
                and img.suffix.lower() in IMAGE_EXTENSIONS
            ):

                actual_records.append({
                    "split": split,
                    "class": cls,
                    "filename": img.name,
                    "path": normalize_path(img)
                })

actual_df = pd.DataFrame(actual_records)

print(
    f"\nActual image records: {len(actual_df):,}"
)

print(
    actual_df.head()
)

================================================================================
CHECKING METADATA ↔ ACTUAL IMAGE MAPPING
================================================================================

Actual image records: 10,690
   split      class                       filename  \
0  train  Cardboard  INTL__Cardboard(345)_aug2.jpg
1  train  Cardboard  INTL__Cardboard(382)_aug4.jpg
2  train  Cardboard  INTL__Cardboard(212)_aug1.jpg
3  train  Cardboard  INTL__Cardboard(424)_aug2.jpg
4  train  Cardboard  INTL__Cardboard(329)_aug2.jpg

                                                path
0  /kaggle/input/notebooks/kbmhkhan/full-final-da...
1  /kaggle/input/notebooks/kbmhkhan/full-final-da...
2  /kaggle/input/notebooks/kbmhkhan/full-final-da...
3  /kaggle/input/notebooks/kbmhkhan/full-final-da...
4  /kaggle/input/notebooks/kbmhkhan/full-final-da...

In [20]:
# ============================================================
# STEP 5 — INSPECT METADATA COLUMNS
# ============================================================

print("=" * 80)
print("METADATA COLUMNS")
print("=" * 80)

print(list(train_df.columns))

print("\nSample metadata:")
display(train_df.head())

================================================================================
METADATA COLUMNS
================================================================================
['filename', 'class', 'source', 'country', 'dataset_group', 'original_path']

Sample metadata:

,filename,class,source,country,dataset_group,original_path
0,INTL__Metal(341)_aug1.jpg,Metal,International,International,International,/kaggle/input/datasets/kbmhkhan/waste-classifi...
1,INTL__Paper(418)_aug4.jpg,Paper,International,International,International,/kaggle/input/datasets/kbmhkhan/waste-classifi...
2,INTL__Cardboard(372)_aug4.jpg,Cardboard,International,International,International,/kaggle/input/datasets/kbmhkhan/waste-classifi...
3,INTL__Plastic(245)_aug2.jpg,Plastic,International,International,International,/kaggle/input/datasets/kbmhkhan/waste-classifi...
4,INTL__Glass(48)_aug2.jpg,Glass,International,International,International,/kaggle/input/datasets/kbmhkhan/waste-classifi...

In [21]:
# ============================================================
# STEP 6 — FIND EXTRA IMAGES NOT PRESENT IN METADATA
# ============================================================

print("=" * 80)
print("STEP 6 — METADATA ↔ ACTUAL FILENAME COMPARISON")
print("=" * 80)

# ------------------------------------------------------------
# Metadata filenames
# ------------------------------------------------------------

metadata_filenames = set(
    train_df["filename"].astype(str).str.strip()
)

metadata_filenames.update(
    val_df["filename"].astype(str).str.strip()
)

metadata_filenames.update(
    test_df["filename"].astype(str).str.strip()
)

print(f"Unique metadata filenames : {len(metadata_filenames):,}")

# ------------------------------------------------------------
# Actual filenames
# ------------------------------------------------------------

actual_filenames = set(
    actual_df["filename"].astype(str).str.strip()
)

print(f"Unique actual filenames   : {len(actual_filenames):,}")

# ------------------------------------------------------------
# Differences
# ------------------------------------------------------------

extra_images = sorted(
    actual_filenames - metadata_filenames
)

missing_images = sorted(
    metadata_filenames - actual_filenames
)

print("\n" + "-" * 80)

print(
    f"Extra actual images       : {len(extra_images):,}"
)

print(
    f"Metadata images missing   : {len(missing_images):,}"
)

# ------------------------------------------------------------
# Show extra images
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("EXTRA ACTUAL IMAGES")
print("=" * 80)

if extra_images:

    for filename in extra_images:
        print(filename)

else:
    print("✓ No extra images found")

# ------------------------------------------------------------
# Show missing images
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("MISSING ACTUAL IMAGES")
print("=" * 80)

if missing_images:

    for filename in missing_images:
        print(filename)

else:
    print("✓ No metadata images are missing")

================================================================================
STEP 6 — METADATA ↔ ACTUAL FILENAME COMPARISON
================================================================================
Unique metadata filenames : 10,668
Unique actual filenames   : 10,690

--------------------------------------------------------------------------------
Extra actual images       : 22
Metadata images missing   : 0

================================================================================
EXTRA ACTUAL IMAGES
================================================================================
BD__EWaste__test__IMG_20250822_141136_jpg.rf.0be4d2fca3b4f606057e95da0a6c36a2__obj0.jpg
BD__EWaste__test__IMG_20250822_141139_jpg.rf.36eed639860f3a1bf6f903767cf549bb__obj0.jpg
BD__EWaste__test__IMG_20250822_141837_jpg.rf.13bec81f6c9e8f0b6fd2782947f9d949__obj0.jpg
BD__EWaste__test__IMG_20250822_141854_jpg.rf.26893559ba0d9f4492b376d05a1fcd02__obj0.jpg
BD__EWaste__train__IMG_20250805_204158_jpg.rf.83f1e8426c72186415b229cf61e3ec7f__obj0.jpg
BD__EWaste__train__IMG_20250805_204240_jpg.rf.eb698695bfc2e063c66a3629867f5058__obj0.jpg
BD__EWaste__train__IMG_20250805_204241_jpg.rf.6f6b3df4d4bd9f7c0ddf7a4f4f8bee53__obj0.jpg
BD__EWaste__train__IMG_20250805_204241_jpg.rf.8c3704f64d7cd9886b07a98cd79ca356__obj0.jpg
BD__EWaste__train__IMG_20250805_204242_jpg.rf.954bdd581387fcb523d672277e062514__obj0.jpg
BD__EWaste__train__IMG_20250805_204242_jpg.rf.ea24d69a343d670177e310f7ef85814c__obj0.jpg
BD__EWaste__train__IMG_20250805_205143_jpg.rf.aefcc90f62c9f9cc7ae8e623fcf78c1f__obj0.jpg
BD__EWaste__train__IMG_20250820_000335_1_jpg.rf.ff22b9861989d50974b4921d7d2cefcd__obj0.jpg
BD__EWaste__train__IMG_20250822_141138_jpg.rf.52689dea72210310654694b117c0a636__obj0.jpg
BD__EWaste__train__IMG_20250822_141141_jpg.rf.031cb8b6f6b4889a8fa742d84b003944__obj0.jpg
BD__EWaste__train__IMG_20250822_141826_jpg.rf.15d4df7fe3ae43438828e772b0ea7a7b__obj0.jpg
BD__EWaste__train__IMG_20250822_141826_jpg.rf.54132f7b21553fab2a869e2958f80a8e__obj0.jpg
BD__EWaste__train__IMG_20250822_141838_jpg.rf.7e227739cbd2ce1bd68a6317596acb53__obj0.jpg
BD__EWaste__train__IMG_20250822_141857_jpg.rf.3b3db3eb2086f7446b43cf62ec68a5b7__obj0.jpg
BD__EWaste__train__IMG_20250822_141857_jpg.rf.4b156c3209fe9e39f20a4170e7891fb2__obj0.jpg
BD__EWaste__train__IMG_20250822_141857_jpg.rf.5a8171772b69478d994d37def815cb43__obj0.jpg
BD__EWaste__train__IMG_20250822_142140_jpg.rf.12688068d2bc49068b201ac32289690b__obj0.jpg
BD__EWaste__train__IMG_20250822_142146_jpg.rf.a6aeef063cee2b721563d821213c8733__obj0.jpg

================================================================================
MISSING ACTUAL IMAGES
================================================================================
✓ No metadata images are missing

In [22]:
# ============================================================
# STEP 7 — EXACT RESEARCH DATASET FREEZE
# ============================================================

print("=" * 80)
print("STEP 7 — EXACT RESEARCH DATASET FREEZE")
print("=" * 80)

# ------------------------------------------------------------
# Metadata filenames
# ------------------------------------------------------------

metadata_files = set(
    train_df["filename"].astype(str).str.strip()
)

metadata_files.update(
    val_df["filename"].astype(str).str.strip()
)

metadata_files.update(
    test_df["filename"].astype(str).str.strip()
)

# ------------------------------------------------------------
# Actual filenames
# ------------------------------------------------------------

actual_files = set(
    actual_df["filename"].astype(str).str.strip()
)

# ------------------------------------------------------------
# Exact research dataset
# ------------------------------------------------------------

research_files = metadata_files.intersection(actual_files)

# Extra files
extra_files = actual_files - metadata_files

# Missing files
missing_files = metadata_files - actual_files

print("\n" + "-" * 80)
print("RESULT")
print("-" * 80)

print(f"Metadata images       : {len(metadata_files):,}")
print(f"Actual images         : {len(actual_files):,}")
print(f"Research images       : {len(research_files):,}")
print(f"Extra actual images   : {len(extra_files):,}")
print(f"Missing actual images : {len(missing_files):,}")

print("\n" + "-" * 80)

if len(research_files) == 10668:
    print("✓ EXACT 10,668 RESEARCH IMAGES FOUND")
else:
    print("⚠ RESEARCH IMAGE COUNT DOES NOT MATCH")

if len(missing_files) == 0:
    print("✓ NO METADATA IMAGE IS MISSING")
else:
    print("⚠ SOME METADATA IMAGES ARE MISSING")

print("\n✓ Extra images will NOT be used.")
print("✓ No dataset image will be deleted.")
print("✓ Metadata remains unchanged.")

================================================================================
STEP 7 — EXACT RESEARCH DATASET FREEZE
================================================================================

--------------------------------------------------------------------------------
RESULT
--------------------------------------------------------------------------------
Metadata images       : 10,668
Actual images         : 10,690
Research images       : 10,668
Extra actual images   : 22
Missing actual images : 0

--------------------------------------------------------------------------------
✓ EXACT 10,668 RESEARCH IMAGES FOUND
✓ NO METADATA IMAGE IS MISSING

✓ Extra images will NOT be used.
✓ No dataset image will be deleted.
✓ Metadata remains unchanged.

In [23]:
# ============================================================
# STEP 8 — INSPECT EXTRA IMAGES
# ============================================================

print("=" * 80)
print("STEP 8 — EXTRA IMAGE INSPECTION")
print("=" * 80)

extra_df = actual_df[
    actual_df["filename"].isin(extra_files)
].copy()

print(f"\nExtra images found: {len(extra_df):,}")

print("\nSplit distribution:")
print(
    extra_df["split"]
    .value_counts()
    .sort_index()
)

print("\nClass distribution:")
print(
    extra_df["class"]
    .value_counts()
    .sort_index()
)

print("\nDetailed list:")
display(
    extra_df[
        ["split", "class", "filename", "path"]
    ].sort_values(
        ["split", "class", "filename"]
    )
)

================================================================================
STEP 8 — EXTRA IMAGE INSPECTION
================================================================================

Extra images found: 22

Split distribution:
split
test           9
train         10
validation     3
Name: count, dtype: int64

Class distribution:
class
Metal      18
Plastic     4
Name: count, dtype: int64

Detailed list:

,split,class,filename,path
9758,test,Metal,BD__EWaste__test__IMG_20250822_141136_jpg.rf.0...,/kaggle/input/notebooks/kbmhkhan/full-final-da...
9703,test,Metal,BD__EWaste__test__IMG_20250822_141837_jpg.rf.1...,/kaggle/input/notebooks/kbmhkhan/full-final-da...
9744,test,Metal,BD__EWaste__test__IMG_20250822_141854_jpg.rf.2...,/kaggle/input/notebooks/kbmhkhan/full-final-da...
9465,test,Metal,BD__EWaste__train__IMG_20250805_204158_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
9828,test,Metal,BD__EWaste__train__IMG_20250805_204240_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
9728,test,Metal,BD__EWaste__train__IMG_20250822_141141_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
9581,test,Metal,BD__EWaste__train__IMG_20250822_141826_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
9826,test,Metal,BD__EWaste__train__IMG_20250822_141857_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
10660,test,Plastic,BD__EWaste__train__IMG_20250805_205143_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
4071,train,Metal,BD__EWaste__test__IMG_20250822_141139_jpg.rf.3...,/kaggle/input/notebooks/kbmhkhan/full-final-da...
4017,train,Metal,BD__EWaste__train__IMG_20250805_204241_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
2919,train,Metal,BD__EWaste__train__IMG_20250805_204241_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
3938,train,Metal,BD__EWaste__train__IMG_20250805_204242_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
3580,train,Metal,BD__EWaste__train__IMG_20250805_204242_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
3706,train,Metal,BD__EWaste__train__IMG_20250822_141138_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
3646,train,Metal,BD__EWaste__train__IMG_20250822_141826_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
2929,train,Metal,BD__EWaste__train__IMG_20250822_141857_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
6092,train,Plastic,BD__EWaste__train__IMG_20250822_142140_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
6278,train,Plastic,BD__EWaste__train__IMG_20250822_142146_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
8013,validation,Metal,BD__EWaste__train__IMG_20250822_141838_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
7974,validation,Metal,BD__EWaste__train__IMG_20250822_141857_jpg.rf....,/kaggle/input/notebooks/kbmhkhan/full-final-da...
8761,validation,Plastic,BD__EWaste__train__IMG_20250820_000335_1_jpg.r...,/kaggle/input/notebooks/kbmhkhan/full-final-da...

In [24]:
# ============================================================
# STEP 9 — EXACT RESEARCH SPLIT COUNTS
# ============================================================

print("=" * 80)
print("STEP 9 — EXACT RESEARCH DATASET SPLIT COUNTS")
print("=" * 80)

for split_name, df in [
    ("TRAIN", train_df),
    ("VALIDATION", val_df),
    ("TEST", test_df)
]:

    print(f"\n{split_name}")
    print("-" * 50)

    print(
        df["class"]
        .value_counts()
        .sort_index()
    )

    print(
        f"TOTAL: {len(df):,}"
    )

print("\n" + "=" * 80)

print(
    f"TRAIN      : {len(train_df):,}"
)

print(
    f"VALIDATION : {len(val_df):,}"
)

print(
    f"TEST       : {len(test_df):,}"
)

print(
    f"TOTAL      : {len(train_df) + len(val_df) + len(test_df):,}"
)

================================================================================
STEP 9 — EXACT RESEARCH DATASET SPLIT COUNTS
================================================================================

TRAIN
--------------------------------------------------
class
Cardboard    1193
Glass        1433
Metal        1594
Paper        1793
Plastic      1232
Name: count, dtype: int64
TOTAL: 7,245

VALIDATION
--------------------------------------------------
class
Cardboard    255
Glass        307
Metal        341
Paper        385
Plastic      264
Name: count, dtype: int64
TOTAL: 1,552

TEST
--------------------------------------------------
class
Cardboard    272
Glass        372
Metal        380
Paper        484
Plastic      363
Name: count, dtype: int64
TOTAL: 1,871

================================================================================
TRAIN      : 7,245
VALIDATION : 1,552
TEST       : 1,871
TOTAL      : 10,668

In [25]:
# ============================================================
# STEP 10 — CLASS DISTRIBUTION FREEZE
# ============================================================

print("=" * 80)
print("STEP 10 — CLASS DISTRIBUTION FREEZE")
print("=" * 80)

for split_name, df in [
    ("TRAIN", train_df),
    ("VALIDATION", val_df),
    ("TEST", test_df)
]:

    counts = (
        df["class"]
        .value_counts()
        .sort_index()
    )

    print(f"\n{split_name}")
    print("-" * 50)

    for cls in classes:
        print(
            f"{cls:12s}: {counts.get(cls, 0):,}"
        )

print("\n✓ CLASS DISTRIBUTION FROZEN")

================================================================================
STEP 10 — CLASS DISTRIBUTION FREEZE
================================================================================

TRAIN
--------------------------------------------------
Cardboard   : 1,193
Glass       : 1,433
Metal       : 1,594
Paper       : 1,793
Plastic     : 1,232

VALIDATION
--------------------------------------------------
Cardboard   : 255
Glass       : 307
Metal       : 341
Paper       : 385
Plastic     : 264

TEST
--------------------------------------------------
Cardboard   : 272
Glass       : 372
Metal       : 380
Paper       : 484
Plastic     : 363

✓ CLASS DISTRIBUTION FROZEN

In [26]:
# ============================================================
# STEP 11 — INVESTIGATE 10,688 vs 10,668
# ============================================================

print("=" * 80)
print("STEP 11 — DATASET COUNT DISCREPANCY INVESTIGATION")
print("=" * 80)

print("""
Expected earlier unified dataset : 10,688
Current metadata                 : 10,668
Current actual dataset            : 10,690

We will NOT modify anything.
We only inspect the counts.
""")

print("\nCurrent metadata:")
print(f"Train      : {len(train_df):,}")
print(f"Validation : {len(val_df):,}")
print(f"Test       : {len(test_df):,}")
print(f"TOTAL      : {len(train_df)+len(val_df)+len(test_df):,}")

print("\nCurrent actual:")
print(f"Train      : {actual_counts['train']:,}")
print(f"Validation : {actual_counts['validation']:,}")
print(f"Test       : {actual_counts['test']:,}")
print(f"TOTAL      : {sum(actual_counts.values()):,}")

print("\nDifferences:")
print(
    f"Metadata vs expected 10,688 : "
    f"{10668 - 10688:+,}"
)

print(
    f"Actual vs metadata           : "
    f"{10690 - 10668:+,}"
)

print(
    f"Actual vs expected 10,688    : "
    f"{10690 - 10688:+,}"
)

================================================================================
STEP 11 — DATASET COUNT DISCREPANCY INVESTIGATION
================================================================================

Expected earlier unified dataset : 10,688
Current metadata                 : 10,668
Current actual dataset            : 10,690

We will NOT modify anything.
We only inspect the counts.


Current metadata:
Train      : 7,245
Validation : 1,552
Test       : 1,871
TOTAL      : 10,668

Current actual:
Train      : 7,255
Validation : 1,555
Test       : 1,880
TOTAL      : 10,690

Differences:
Metadata vs expected 10,688 : -20
Actual vs metadata           : +22
Actual vs expected 10,688    : +2

# DATASET DIAGNOSTIC — DO NOT MODIFY DATA

In [27]:
# ============================================================
# DATASET DIAGNOSTIC — DO NOT MODIFY DATA
# ============================================================

print("=" * 80)
print("DATASET DIAGNOSTIC")
print("=" * 80)

print("\nMetadata:")
print(f"Train      : {len(train_df):,}")
print(f"Validation : {len(val_df):,}")
print(f"Test       : {len(test_df):,}")
print(f"Total      : {len(train_df) + len(val_df) + len(test_df):,}")

print("\nActual:")
print(f"Train      : {actual_counts['train']:,}")
print(f"Validation : {actual_counts['validation']:,}")
print(f"Test       : {actual_counts['test']:,}")
print(f"Total      : {sum(actual_counts.values()):,}")

================================================================================
DATASET DIAGNOSTIC
================================================================================

Metadata:
Train      : 7,245
Validation : 1,552
Test       : 1,871
Total      : 10,668

Actual:
Train      : 7,255
Validation : 1,555
Test       : 1,880
Total      : 10,690

# EXACT CLASS COUNTS

In [28]:
# ============================================================
# EXACT CLASS COUNTS
# ============================================================

for name, df in [
    ("TRAIN", train_df),
    ("VALIDATION", val_df),
    ("TEST", test_df)
]:

    print("\n" + "=" * 60)
    print(name)

    counts = (
        df["class"]
        .value_counts()
        .sort_index()
    )

    print(counts)
    print("TOTAL:", len(df))

============================================================
TRAIN
class
Cardboard    1193
Glass        1433
Metal        1594
Paper        1793
Plastic      1232
Name: count, dtype: int64
TOTAL: 7245

============================================================
VALIDATION
class
Cardboard    255
Glass        307
Metal        341
Paper        385
Plastic      264
Name: count, dtype: int64
TOTAL: 1552

============================================================
TEST
class
Cardboard    272
Glass        372
Metal        380
Paper        484
Plastic      363
Name: count, dtype: int64
TOTAL: 1871

In [29]:
# ============================================================
# STEP 1 — FIND DATASET ROOT
# ============================================================

from pathlib import Path

BASE = Path("/kaggle/input")

for p in BASE.iterdir():
    print(p)

/kaggle/input/notebooks

In [30]:
# ============================================================
# STEP 2 — INSPECT KAGGLE INPUT
# ============================================================

for p in Path("/kaggle/input").rglob("*"):
    if p.is_dir():
        print(p)

/kaggle/input/notebooks
/kaggle/input/notebooks/kbmhkhan
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code
/kaggle/input/notebooks/kbmhkhan/model-training-setup-1st-model-run
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Waste_Dataset_Research_Metadata
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Dataset_Reports
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/BDWaste_5Class
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/A_waste_management_converted
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/A_waste_5Class
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/EWaste_5Class_Crops
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Bangladesh_5Class
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/BDWaste_4Class
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/__results___files
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Bangladesh_5Class_Clean
/kaggle/input/notebooks/kbmhkhan/model-training-setup-1st-model-run/Dataset_Reports
/kaggle/input/notebooks/kbmhkhan/model-training-setup-1st-model-run/__results___files
/kaggle/input/notebooks/kbmhkhan/model-training-setup-1st-model-run/waste_model_results
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/metadata
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test_international
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test_bangladesh
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/train
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset/research_metadata
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset/images
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Dataset_Reports/final_review_contact_sheets
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Dataset_Reports/flagged_contact_sheets
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/BDWaste_5Class/Glass
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/BDWaste_5Class/Paper
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/BDWaste_5Class/Cardboard
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/BDWaste_5Class/Plastic
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/A_waste_management_converted/Plastic
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/A_waste_5Class/Glass
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/A_waste_5Class/Paper
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/A_waste_5Class/Plastic
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/EWaste_5Class_Crops/Metal
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/EWaste_5Class_Crops/Glass
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/EWaste_5Class_Crops/Paper
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/EWaste_5Class_Crops/Plastic
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Bangladesh_5Class/Metal
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Bangladesh_5Class/Glass
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Bangladesh_5Class/Paper
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Bangladesh_5Class/Cardboard
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Bangladesh_5Class/Plastic
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/BDWaste_4Class/Glass
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/BDWaste_4Class/Paper
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/BDWaste_4Class/Cardboard
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/BDWaste_4Class/Plastic
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Bangladesh_5Class_Clean/Metal
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Bangladesh_5Class_Clean/Glass
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Bangladesh_5Class_Clean/Paper
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Bangladesh_5Class_Clean/Cardboard
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Bangladesh_5Class_Clean/Plastic
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Metal
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Glass
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Paper
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Cardboard
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/validation/Plastic
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test_international/Metal
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test_international/Glass
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test_international/Paper
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test_international/Cardboard
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test_international/Plastic
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test_bangladesh/Metal
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test_bangladesh/Glass
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test_bangladesh/Paper
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test_bangladesh/Cardboard
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test_bangladesh/Plastic
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test/Metal
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test/Glass
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test/Paper
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test/Cardboard
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/test/Plastic
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/train/Metal
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/train/Glass
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/train/Paper
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/train/Cardboard
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset_Split/train/Plastic
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset/images/Metal
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset/images/Glass
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset/images/Paper
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset/images/Cardboard
/kaggle/input/notebooks/kbmhkhan/full-final-dataset-code/Final_Waste_Dataset/images/Plastic
/kaggle/input/notebooks/kbmhkhan/model-training-setup-1st-model-run/waste_model_results/checkpoints
/kaggle/input/notebooks/kbmhkhan/model-training-setup-1st-model-run/waste_model_results/resnet50_experiments
/kaggle/input/notebooks/kbmhkhan/model-training-setup-1st-model-run/waste_model_results/logs
/kaggle/input/notebooks/kbmhkhan/model-training-setup-1st-model-run/waste_model_results/resnet50_experiments/E3_adamw_cosine
/kaggle/input/notebooks/kbmhkhan/model-training-setup-1st-model-run/waste_model_results/resnet50_experiments/E2_strong_augmentation
/kaggle/input/notebooks/kbmhkhan/model-training-setup-1st-model-run/waste_model_results/resnet50_experiments/E5_high_resolution
/kaggle/input/notebooks/kbmhkhan/model-training-setup-1st-model-run/waste_model_results/resnet50_experiments/E4_label_smoothing